import "./../_styles/globals.css";
import type { Metadata } from "next";
import { Reddit_Sans } from "next/font/google";
// import "./../../_styles/globals.css";
import ConvexClientProvider from "../ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";

const redditSans = Reddit_Sans({
  variable: "--font-reddit-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${redditSans.className} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
